# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/chirpminds',
                'doc_host': 'https://leoank.github.io',
                'git_url': 'https://github.com/leoank/chirpminds',
                'lib_path': 'src/chirpminds'},
  'syms': { 'chirpminds.download': {'chirpminds.download.download_file': ('download_gdrive.html#download_file', 'chirpminds/download.py')},
            'chirpminds.labelstudio': { 'chirpminds.labelstudio.setup_project': ( 'setup_annotation_project.html#setup_project',
                                                                                  'chirpminds/labelstudio.py')},
            'chirpminds.process_video': { 'chirpminds.process_video.extract_frame': ( 'process_video.html#extract_frame',
                                                                                      'chirpminds/process_video.py'),
                                          'chirpminds.process_video.extract_frames': ( 'process_video.html#extract_frames',
                                                                                       'chirpminds/process_video.py'),
                                          'chirpminds.process_video.get_video_info': ( 'process_video.html#get_video_info',
                                                                                       'chirpminds/process_video.py')},
            'chirpminds.utils': {'chirpminds.utils.download_file': ('download_gdrive.html#download_file', 'chirpminds/utils.py')}}}
