# AUTOGENERATED! DO NOT EDIT! File to edit: ../../notebooks/ipynb/000_download_gdrive.ipynb.

# %% auto 0
__all__ = ['download_file']

# %% ../../notebooks/ipynb/000_download_gdrive.ipynb 3
from pathlib import Path

import gdown
from tqdm import tqdm

from .utils import parallel

# %% ../../notebooks/ipynb/000_download_gdrive.ipynb 6
def download_file(file_name_list: list[str], file_map: dict[str, str], job_id: int) -> None:
    for file_name in tqdm(file_name_list, position=job_id):
        gdown.download(id=file_name, output=file_map[file_name])
